# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/preferences.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_preferencesDialog(object):
    def setupUi(self, preferencesDialog):
        preferencesDialog.setObjectName("preferencesDialog")
        preferencesDialog.resize(562, 423)
        preferencesDialog.setStyleSheet("QWidget#frmLogin,QWidget#frmPopup,QWidget#frmHostInfo,QWidget#frmLogout,QWidget#frmConfig,QWidget#frmData,QWidget#frmDefence,QWidget#frmHost,QWidget#frmMain,QWidget#frmPwd,QWidget#frmSelect,QWidget#frmMessageBox{\n"
"    border:1px solid #1B89CA;\n"
"    border-radius:0px;    \n"
"}\n"
"\n"
".QFrame{\n"
"    border:1px solid #5CACEE;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QWidget#widget_title{\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5);\n"
"}\n"
"\n"
"QLabel#lab_Ico,QLabel#lab_Title{\n"
"    border-radius:0px;\n"
"    color: #F0F0F0;\n"
"    background-color:rgba(0,0,0,0);\n"
"    border-style:none;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #5CACEE;\n"
"    border-radius: 5px;\n"
"    padding: 2px;\n"
"    background: none;\n"
"    selection-background-color: #1B89CA;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] { \n"
"    lineedit-password-character: 9679; \n"
"}\n"
"\n"
".QGroupBox{\n"
"    border: 1px solid #5CACEE;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
".QPushButton{\n"
"    border-style: none;\n"
"    border: 0px;\n"
"    color: #F0F0F0;\n"
"    padding: 5px;    \n"
"    min-height: 20px;\n"
"    border-radius:5px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
".QPushButton[focusPolicy=\"0\"] {\n"
"    border-style: none;\n"
"    border: 0px;\n"
"    color: #F0F0F0;\n"
"    padding: 0px;    \n"
"    min-height: 10px;\n"
"    border-radius:3px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
".QPushButton:hover{ \n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD);\n"
"}\n"
"\n"
".QPushButton:pressed{ \n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5);\n"
"}\n"
"\n"
"QPushButton#btnMenu,QPushButton#btnMenu_Min,QPushButton#btnMenu_Max,QPushButton#btnMenu_Close{\n"
"    border-radius:0px;\n"
"    color: #F0F0F0;\n"
"    background-color:rgba(0,0,0,0);\n"
"    border-style:none;\n"
"}\n"
"\n"
"QPushButton#btnMenu:hover,QPushButton#btnMenu_Min:hover,QPushButton#btnMenu_Max:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(25, 134, 199, 0), stop:1 #5CACEE);\n"
"}\n"
"\n"
"QPushButton#btnMenu_Close:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(238, 0, 0, 128), stop:1 rgba(238, 44, 44, 255));\n"
"}\n"
"\n"
"QCheckBox {\n"
"    spacing: 2px; \n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/qss-icons/resources/qss-icons/checkbox_unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/qss-icons/resources/qss-icons/checkbox_checked.png); \n"
"}\n"
"\n"
"QRadioButton {\n"
"    spacing: 2px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px; \n"
"    height: 15px; \n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    image: url(:/qss-icons/resources/qss-icons/radio_normal.png); \n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    image: url(:/qss-icons/resources/qss-icons/radio_selected.png); \n"
"}\n"
"\n"
"QComboBox,QDateEdit{\n"
"    border-radius: 3px;\n"
"    padding: 1px 10px 1px 5px;\n"
"    border: 1px solid #5CACEE;\n"
"}\n"
"\n"
"QComboBox::drop-down,QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px; \n"
"    border-left-width: 1px;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    border-left-color: #5CACEE;\n"
"}\n"
"\n"
"QComboBox::down-arrow,QDateEdit::down-arrow {\n"
"    background-color:transparent;\n"
"    image: url(:/qss-icons/resources/qss-icons/array_down.png);\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color:#F0F0F0;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenu::item {    \n"
"    padding: 2px 12px 2px 12px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    color: #FFFFFF;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: #5CACEE;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    border: 1px solid #5CACEE;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    width: 5px; \n"
"    margin: 0.5px;\n"
"    background-color: #1B89CA;\n"
"}\n"
"\n"
"QSlider::groove:horizontal,QSlider::add-page:horizontal { \n"
"    background: #808080; \n"
"    height: 8px; \n"
"    border-radius: 3px; \n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    height: 8px; \n"
"    border-radius: 3px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 13px; \n"
"    margin-top: -3px; \n"
"    margin-bottom: -3px; \n"
"    border-radius: 6px;\n"
"    background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,stop:0.6 #F0F0F0, stop:0.778409 #5CACEE);\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: qradialgradient(spread: pad, cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, stop: 0.6 #F0F0F0,stop:0.778409 #1B89CA);\n"
"}\n"
"\n"
"QSlider::groove:vertical,QSlider::sub-page:vertical {\n"
"    background:#808080; \n"
"    width: 8px; \n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    width: 8px;\n"
"    border-radius: 3px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 14px; \n"
"    margin-left: -3px;\n"
"    margin-right: -3px;\n"
"    border-radius: 6px;\n"
"    background: qradialgradient(spread: pad, cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, stop: 0.6 #F0F0F0, stop:0.778409 #5CACEE);\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"    background: qradialgradient(spread: pad, cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5, stop: 0.6 #F0F0F0,stop:0.778409 #1B89CA);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width:10px; \n"
"    background-color:rgba(0,0,0,0%); \n"
"    padding-top:10px; \n"
"    padding-bottom:10px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height:10px; \n"
"    background-color:rgba(0,0,0,0%); \n"
"    padding-left:10px; padding-right:10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    width:10px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD); \n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    height:10px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD); \n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    width:10px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    height:10px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    height:10px;\n"
"    width:10px;\n"
"    subcontrol-position: bottom; \n"
"    subcontrol-origin: margin;\n"
"    border-image: url(:/qss-icons/resources/qss-icons/add-line_vertical.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    height:10px;\n"
"    width:10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"    border-image: url(:/qss-icons/resources/qss-icons/add-line_horizontal.png);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height:10px;\n"
"    width:10px;\n"
"    subcontrol-position: top; \n"
"    subcontrol-origin: margin;\n"
"    border-image: url(:/qss-icons/resources/qss-icons/sub-line_vertical.png);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    height:10px;\n"
"    width:10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"    border-image: url(:/qss-icons/resources/qss-icons/sub-line_horizontal.png);\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical {\n"
"    width:10px;\n"
"    background: #C0C0C0;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal {\n"
"    height:10px;\n"
"    background: #C0C0C0;\n"
"}\n"
"\n"
"QScrollArea {\n"
"    border: 0px ; \n"
"}\n"
"\n"
"QTreeView,QListView,QTableView{\n"
"    border: 1px solid #5CACEE; \n"
"    selection-background-color: #1B89CA;\n"
"    selection-color: #F0F0F0;\n"
"}\n"
"\n"
"QTableView::item:selected, QListView::item:selected, QTreeView::item:selected {\n"
"    color: #F0F0F0;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QTableView::item:hover, QListView::item:hover, QTreeView::item:hover {\n"
"    color: #F0F0F0;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD); \n"
"}\n"
"\n"
"QTableView::item, QListView::item, QTreeView::item {\n"
"    padding: 5px; \n"
"    margin: 0px; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    padding:3px;\n"
"    margin:0px;\n"
"    color:#F0F0F0;\n"
"    border: 1px solid #F0F0F0;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-bottom-left-radius:0px;\n"
"    border-bottom-right-radius:0px;\n"
"    color: #F0F0F0;\n"
"    min-width: 60px;\n"
"    min-height: 20px;\n"
"    padding: 3px 8px 3px 8px;\n"
"    margin:1px;\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #5CACEE, stop:1 #4F94CD); \n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #1B89CA, stop:1 #1077B5); \n"
"}\n"
"\n"
"QStatusBar::item {\n"
"     border: 1px solid #5CACEE;\n"
"     border-radius: 3px;\n"
"}\n"
"\n"
"QMainWindow {\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.4 rgb(194, 216, 242),\n"
"                                 stop: 0.4 rgb(194, 216, 242), stop: 1.0 rgb(156, 193, 239));\n"
"  color:rgb(59, 90, 130);\n"
"}\n"
"\n"
"QWidget{\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.4 rgb(194, 216, 242),\n"
"                                 stop: 0.4 rgb(194, 216, 242), stop: 1.0 rgb(156, 193, 239));\n"
"  color:rgb(59, 90, 130);\n"
"}\n"
"\n"
"QDockWidget > QWidget  {\n"
"  border-style:none;\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.4 rgb(194, 216, 242),\n"
"                                 stop: 0.4 rgb(194, 216, 242), stop: 1.0 rgb(156, 193, 239));\n"
"  \n"
"  padding:1px;\n"
"  border-radius: 0px;\n"
"  \n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QWidget > QDockWidget  {\n"
"   background:white;\n"
"}\n"
"\n"
"QCalendarWidget > QWidget > QToolButton {\n"
"  border-style:none;\n"
"  color:rgb(59, 90, 130);\n"
"  background:transparent;\n"
"  padding:1px;\n"
"  border-radius: 0px;\n"
"}\n"
"\n"
"QCalendarWidget > QWidget#qt_calendar_navigationbar{\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  background:transparent;\n"
"  border-top-left-radius: 8px;\n"
"  border-top-right-radius: 8px;    \n"
"}\n"
"\n"
"QCalendarWidget > QWidget#qt_calendar_calendarview  {\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  background:white;\n"
"  border-radius: 0px;\n"
"  border-bottom-left-radius: 8px;\n"
"  border-bottom-right-radius: 8px;        \n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 3px;\n"
"}\n"
"\n"
"QTabWidget::pane {  \n"
"   margin: 1px, 1px, 1px, 1px;\n"
"   border-left: 1px solid rgb(255, 255, 255);\n"
"   border-top: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 2px solid rgb(136, 163, 205);\n"
"   border-right: 2px solid rgb(136, 163, 205);\n"
"   border-radius: 8px;\n"
"   border-top-left-radius: 0px;\n"
"   padding: 0px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"  background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.4 rgb(194, 216, 242),\n"
"                                 stop: 0.4 rgb(194, 216, 242), stop: 1.0 rgb(217, 231, 247));\n"
"  border-left: 1px solid rgb(255, 255, 255);\n"
"  border-top: 1px solid rgb(255, 255, 255);\n"
"  border-bottom: 1px solid rgb(136, 163, 205);\n"
"  border-right: 1px solid rgb(136, 163, 205);\n"
"  border-top-right-radius: 15;\n"
"  border-top-left-radius: 5;    \n"
"  color:rgb(59, 90, 130);\n"
"  padding:5px;\n"
"  min-width: 80px;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected {\n"
"margin-top: 3px; /* make non-selected tabs look smaller */\n"
"} \n"
"\n"
"QTabBar::tab:first {\n"
"  background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.4 rgb(194, 216, 242),\n"
"                                 stop: 0.4 rgb(194, 216, 242), stop: 1.0 rgb(217, 231, 247));\n"
"\n"
"  border-left: 1px solid rgb(255, 255, 255);\n"
"  border-top: 1px solid rgb(255, 255, 255);\n"
"  border-bottom: 1px solid rgb(136, 163, 205);\n"
"  border-right: 1px solid rgb(136, 163, 205);\n"
"  border-top-right-radius: 15;\n"
"  border-top-left-radius: 5;    \n"
"  color:rgb(59, 90, 130);\n"
"  padding:5px;\n"
"}\n"
"\n"
"QTabBar::tab::selected {\n"
"  background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.8 rgb(194, 216, 242),\n"
"                                 stop: 0.2 rgb(194, 216, 242), stop: 1.0 rgb(217, 231, 247));\n"
"  border-left: 1px solid rgb(255, 255, 255);\n"
"  border-top: 1px solid rgb(255, 255, 255);\n"
"  border-bottom: 1px solid rgb(136, 163, 205);\n"
"  border-right: 2px solid rgb(136, 163, 205);\n"
"  border-top-right-radius: 15;\n"
"  border-top-left-radius: 5;    \n"
"  color:rgb(59, 90, 130);\n"
"  padding:5px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"left: 0px; /* move to the right by 5px */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0  rgb(217, 231, 247), stop: 0.8 rgb(194, 216, 242),\n"
"stop: 0.2 rgb(194, 216, 242), stop: 1.0 rgb(217, 231, 247));\n"
"}    \n"
"\n"
"QPushButton:hover, QToolButton:hover, QCheckBox:hover, QRadioButton:hover {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0  rgb(217, 231, 247), stop: 0.8 rgb(194, 216, 242),\n"
"stop: 0.2 rgb(194, 216, 242), stop: 1.0 rgb(217, 231, 247));\n"
"}\n"
" \n"
"QComboBox:!editable {\n"
"   min-width: 80px;  \n"
"   min-height: 19px; \n"
"   background-color:transparent;\n"
"   border-left: 1px solid rgb(255, 255, 255);\n"
"   border-top: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 2px solid rgb(136, 163, 205);\n"
"   border-right: 2px solid rgb(136, 163, 205);\n"
"   background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QComboBox:!editable:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0  rgb(217, 231, 247), stop: 0.8 rgb(194, 216, 242),\n"
"stop: 0.2 rgb(194, 216, 242), stop: 1.0 rgb(217, 231, 247));\n"
"}\n"
"\n"
"QComboBox:!editable:on {\n"
"   min-width: 80px;  \n"
"   min-height: 19px; \n"
"   background:transparent;\n"
"   border-right: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 1px solid rgb(255, 255, 255);\n"
"   border-top: 2px solid rgb(136, 163, 205);\n"
"   border-left: 2px solid rgb(136, 163, 205);\n"
"   background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"   min-width: 80px;  \n"
"   min-height: 18px; \n"
"   border-right: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 1px solid rgb(255, 255, 255);\n"
"   border-top: 2px solid rgb(136, 163, 205);\n"
"   border-left: 2px solid rgb(136, 163, 205);\n"
"   background:white;\n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: transparent;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"}\n"
" \n"
"QComboBox QAbstractItemView {\n"
"   border: 1px solid gray;\n"
"}\n"
"\n"
"QLabel {  \n"
"  background-color:transparent;\n"
"}\n"
"\n"
"QLineEdit, QTextEdit {  \n"
"   background:white;\n"
"   min-width: 80px;  \n"
"   min-height: 16px; \n"
"   border-right: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 1px solid rgb(255, 255, 255);\n"
"   border-top: 2px solid rgb(136, 163, 205);\n"
"   border-left: 2px solid rgb(136, 163, 205);\n"
"   \n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton {  \n"
"   background:transparent;\n"
"   min-width: 80px;  \n"
"   min-height: 20px; \n"
"   border-left: 1px solid rgb(255, 255, 255);\n"
"   border-top: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 2px solid rgb(136, 163, 205);\n"
"   border-right: 2px solid rgb(136, 163, 205);\n"
"   background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  \n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QCheckBox {  \n"
"   background:transparent;\n"
"   min-width: 80px;  \n"
"   min-height: 20px; \n"
"   border-left: 1px solid rgb(255, 255, 255);\n"
"   border-top: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 2px solid rgb(136, 163, 205);\n"
"   border-right: 2px solid rgb(136, 163, 205);\n"
"   background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  \n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton {\n"
"  border-style:none;\n"
"  min-width: 80px;  \n"
"  min-height: 20px;    \n"
"  border-left: 1px solid rgb(255, 255, 255);\n"
"  border-top: 1px solid rgb(255, 255, 255);\n"
"    \n"
"  border-bottom: 2px solid rgb(136, 163, 205);\n"
"  border-right: 2px solid rgb(136, 163, 205);\n"
"  color:rgb(59, 90, 130);\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  padding:3px;\n"
"  border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"  border-style:none;   \n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"    \n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"    \n"
"  color:rgb(59, 90, 130);\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  padding:3px;\n"
"  border-radius: 8px;\n"
"}\n"
"\n"
"QToolButton {\n"
"  border-style:none;\n"
"  min-width: 80px;  \n"
"  min-height: 16px;     \n"
"  border-left: 1px solid rgb(255, 255, 255);\n"
"  border-top: 1px solid rgb(255, 255, 255);\n"
"    \n"
"  border-bottom: 2px solid rgb(136, 163, 205);\n"
"  border-right: 2px solid rgb(136, 163, 205);\n"
"  color:rgb(59, 90, 130);\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  padding:3px;\n"
"  border-radius: 8px;\n"
"}\n"
"\n"
"QCheckBox:checked, QRadioButton:checked {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0  rgb(217, 231, 247), stop: 0.8 rgb(194, 216, 242),\n"
"stop: 0.2 rgb(194, 216, 242), stop: 1.0 rgb(217, 231, 247));\n"
"   border-right: 2px solid rgb(255, 255, 255);\n"
"  border-bottom: 2px solid rgb(255, 255, 255);\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"}\n"
"\n"
"QCheckBox:indeterminate {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0  rgb(217, 231, 247), stop: 0.8 rgb(194, 216, 242),\n"
"stop: 0.2 rgb(194, 216, 242), stop: 1.0 rgb(217, 231, 247));\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"    \n"
"  border-top: 1px solid rgb(136, 163, 205);\n"
"  border-left: 1px solid rgb(136, 163, 205);\n"
"}\n"
"\n"
"\n"
"QToolButton:pressed {\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);  \n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  color:rgb(59, 90, 130);\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  padding:3px;\n"
"  border-radius: 8px;\n"
"}\n"
"\n"
"QMenu{\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  color:rgb(59, 90, 130);\n"
"}\n"
"\n"
"QMenuBar\n"
"{\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  color:rgb(59, 90, 130);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTableView {\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"    \n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  border-radius: 8px;\n"
"  padding: 0 8px;\n"
"  color:rgb(59, 90, 130);\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background: transparent;\n"
"}\n"
"QHeaderView::section {\n"
"    background: transparent;\n"
"    border: 1px solid gray;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QTreeView {\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  color:rgb(59, 90, 130);\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  border-radius: 8px;\n"
"  show-decoration-selected: 0;\n"
"}\n"
"\n"
"QGroupBox{\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  color:rgb(59, 90, 130);\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  border-radius: 8px;\n"
"}\n"
"\n"
"QToolBox {\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  color:rgb(59, 90, 130);\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  border-radius: 8px;\n"
"}\n"
"\n"
"QListWidget {\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  color:rgb(59, 90, 130);\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  border-radius: 8px;\n"
"  show-decoration-selected: 1;\n"
"}\n"
"\n"
"QToolBox > QWidget {\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  color:rgb(59, 90, 130);\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  border-radius: 8px;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"  border-top: 2px solid rgb(136, 163, 205);\n"
"  border-left: 2px solid rgb(136, 163, 205);\n"
"  border-bottom: 1px solid rgb(255, 255, 255);\n"
"  border-right: 1px solid rgb(255, 255, 255);\n"
"  color:rgb(59, 90, 130);\n"
"  background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"  border-radius: 8px;\n"
"}\n"
"\n"
"QSpinBox   {  \n"
"   background:white;\n"
"   border-right: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 1px solid rgb(255, 255, 255);\n"
"   border-top: 2px solid rgb(136, 163, 205);\n"
"   border-left: 2px solid rgb(136, 163, 205);\n"
"   \n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QDoubleSpinBox  {  \n"
"   background:white;\n"
"   border-right: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 1px solid rgb(255, 255, 255);\n"
"   border-top: 2px solid rgb(136, 163, 205);\n"
"   border-left: 2px solid rgb(136, 163, 205);\n"
"   \n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QDateEdit  {  \n"
"   background:white;\n"
"   border-right: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 1px solid rgb(255, 255, 255);\n"
"   border-top: 2px solid rgb(136, 163, 205);\n"
"   border-left: 2px solid rgb(136, 163, 205);\n"
"   \n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QTimeEdit   {  \n"
"   background:white;\n"
"   border-right: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 1px solid rgb(255, 255, 255);\n"
"   border-top: 2px solid rgb(136, 163, 205);\n"
"   border-left: 2px solid rgb(136, 163, 205);\n"
"   \n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QDateTimeEdit   {  \n"
"   background:white;\n"
"   border-right: 1px solid rgb(255, 255, 255);\n"
"   border-bottom: 1px solid rgb(255, 255, 255);\n"
"   border-top: 2px solid rgb(136, 163, 205);\n"
"   border-left: 2px solid rgb(136, 163, 205);\n"
"   \n"
"   padding:3px;\n"
"   border-radius: 8px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-top-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 16px; \n"
"    border-top: 2px solid rgb(136, 163, 205);\n"
" } \n"
" \n"
"QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-top-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 16px; \n"
"    border-top: 2px solid rgb(136, 163, 205);\n"
" } \n"
" \n"
" QDateEdit::up-button  {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-top-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 16px; \n"
"    border-top: 2px solid rgb(136, 163, 205);\n"
" } \n"
" \n"
" QTimeEdit::up-button  {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-top-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 16px; \n"
"    border-top: 2px solid rgb(136, 163, 205);\n"
" } \n"
" \n"
"QDateTimeEdit::up-button  {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-top-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 16px; \n"
"    border-top: 2px solid rgb(136, 163, 205);\n"
" } \n"
"\n"
"QSpinBox::up-arrow{ \n"
"    image: url(:/qss-icons/resources/qss-icons/sub-line_vertical.png)\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow { \n"
"    image: url(:/qss-icons/resources/qss-icons/sub-line_vertical.png)\n"
"}\n"
"\n"
"QDateEdit::up-arrow { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-bottom: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"}\n"
"\n"
"QTimeEdit::up-arrow { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-bottom: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-top-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 15px; \n"
"    border-left: 1px solid #BEBEBE; \n"
"    border-top: 3px solid rgb(136, 163, 205);\n"
" } \n"
" \n"
"QDoubleSpinBox::up-button:pressed {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-top-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 15px; \n"
"    border-left: 1px solid #BEBEBE; \n"
"    border-top: 3px solid rgb(136, 163, 205);\n"
" } \n"
" \n"
" QDateEdit::up-button:pressed  {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-top-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 15px; \n"
"    border-left: 1px solid #BEBEBE; \n"
"    border-top: 3px solid rgb(136, 163, 205);\n"
" } \n"
" \n"
" QTimeEdit::up-button:pressed  {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-top-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 15px; \n"
"    border-left: 1px solid #BEBEBE; \n"
"    border-top: 3px solid rgb(136, 163, 205);\n"
" } \n"
" \n"
"QDateTimeEdit::up-button:pressed  {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: top right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-top-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 15px; \n"
"    border-left: 1px solid #BEBEBE; \n"
"    border-top: 3px solid rgb(136, 163, 205);\n"
" } \n"
" \n"
" QSpinBox::up-arrow:pressed { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-bottom: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"}\n"
"\n"
" QDoubleSpinBox::up-arrow:pressed { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-bottom: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"}\n"
"\n"
" QDateEdit::up-arrow:pressed { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-bottom: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"}\n"
"\n"
" QTimeEdit::up-arrow:pressed { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-bottom: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"}\n"
"\n"
" QSpinBox::down-button {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: bottom right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-bottom-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 16px; \n"
"    border-bottom: 0px;\n"
" } \n"
" \n"
" QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: bottom right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-bottom-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 16px; \n"
"    border-bottom: 0px;\n"
" } \n"
" \n"
"  QDateEdit::down-button {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: bottom right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-bottom-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 16px; \n"
"    border-bottom: 0px;\n"
" } \n"
" \n"
"  QTimeEdit::down-button {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: bottom right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-bottom-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 16px; \n"
"    border-bottom: 0px;\n"
" } \n"
"\n"
" QDateTimeEdit::down-button {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: bottom right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-bottom-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 16px; \n"
"    border-bottom: 0px;\n"
" } \n"
"\n"
"QSpinBox::down-arrow  { \n"
"    image: url(:/qss-icons/resources/qss-icons/array_down.png)\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow { \n"
"    image: url(:/qss-icons/resources/qss-icons/array_down.png)\n"
"}\n"
"\n"
"QDateEdit::down-arrow { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-top: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"}\n"
"\n"
"QTimeEdit::down-arrow { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-top: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"}\n"
"\n"
"QSpinBox::down-button:pressed  {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: bottom right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-bottom-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 14px; \n"
"    border-left: 1px solid #BEBEBE; \n"
"    border-top: 1px solid #BEBEBE; \n"
"    border-right: 1px solid #BEBEBE; \n"
"    border-bottom: 0px;\n"
" } \n"
" \n"
"QDoubleSpinBox::down-button:pressed {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: bottom right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-bottom-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 14px; \n"
"    border-left: 1px solid #BEBEBE; \n"
"    border-top: 1px solid #BEBEBE; \n"
"    border-right: 1px solid #BEBEBE; \n"
"    border-bottom: 0px;\n"
" } \n"
" \n"
" QDateEdit::down-button:pressed  {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: bottom right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-bottom-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 14px; \n"
"    border-left: 1px solid #BEBEBE; \n"
"    border-top: 1px solid #BEBEBE; \n"
"    border-right: 1px solid #BEBEBE; \n"
"    border-bottom: 0px;\n"
" } \n"
" \n"
" QTimeEdit::down-button:pressed  {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: bottom right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-bottom-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 14px; \n"
"    border-left: 1px solid #BEBEBE; \n"
"    border-top: 1px solid #BEBEBE; \n"
"    border-right: 1px solid #BEBEBE; \n"
"    border-bottom: 0px;\n"
" } \n"
" \n"
"QDateTimeEdit::down-button:pressed  {\n"
"    subcontrol-origin: margin; \n"
"    subcontrol-position: bottom right; \n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0  rgb(217, 231, 247), stop: 0.1 rgb(194, 216, 242),\n"
"                                 stop: 0.5 rgb(194, 216, 242), stop: 1.0 rgb(174, 204, 242));\n"
"    border-bottom-right-radius: 8px; \n"
"    border-width: 1px; \n"
"    width: 14px; \n"
"    border-left: 1px solid #BEBEBE; \n"
"    border-top: 1px solid #BEBEBE; \n"
"    border-right: 1px solid #BEBEBE; \n"
"    border-bottom: 0px;\n"
" } \n"
" \n"
"QSpinBox::down-arrow:pressed   { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-top: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow:pressed { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-top: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"}\n"
"\n"
"QDateEdit::down-arrow:pressed { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-top: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"} \n"
" \n"
"QTimeEdit::down-arrow:pressed { \n"
"    background-color: transparent;\n"
"    border-left: 3px solid none;\n"
"    border-right: 3px solid none; \n"
"    border-top: 3px solid #808080; \n"
"    width: 1px; \n"
"    height: 1px; \n"
"} \n"
"\n"
"QHeaderView::section {\n"
"    color: black\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(preferencesDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(preferencesDialog)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 231, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.hp_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.hp_doubleSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.hp_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.hp_doubleSpinBox.setSingleStep(0.1)
        self.hp_doubleSpinBox.setProperty("value", 1.0)
        self.hp_doubleSpinBox.setObjectName("hp_doubleSpinBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hp_doubleSpinBox)
        self.def_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.def_doubleSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.def_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.def_doubleSpinBox.setSingleStep(0.1)
        self.def_doubleSpinBox.setProperty("value", 1.0)
        self.def_doubleSpinBox.setObjectName("def_doubleSpinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.def_doubleSpinBox)
        self.atk_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.atk_doubleSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.atk_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.atk_doubleSpinBox.setSingleStep(0.1)
        self.atk_doubleSpinBox.setProperty("value", 1.0)
        self.atk_doubleSpinBox.setObjectName("atk_doubleSpinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.atk_doubleSpinBox)
        self.spd_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spd_doubleSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.spd_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 50))
        self.spd_doubleSpinBox.setSingleStep(0.1)
        self.spd_doubleSpinBox.setProperty("value", 1.2)
        self.spd_doubleSpinBox.setObjectName("spd_doubleSpinBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spd_doubleSpinBox)
        self.gridLayout_2.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cr_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.cr_doubleSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.cr_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cr_doubleSpinBox.setSingleStep(0.1)
        self.cr_doubleSpinBox.setProperty("value", 1.8)
        self.cr_doubleSpinBox.setObjectName("cr_doubleSpinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cr_doubleSpinBox)
        self.cd_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.cd_doubleSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.cd_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cd_doubleSpinBox.setSingleStep(0.1)
        self.cd_doubleSpinBox.setProperty("value", 1.8)
        self.cd_doubleSpinBox.setObjectName("cd_doubleSpinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cd_doubleSpinBox)
        self.acc_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.acc_doubleSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.acc_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.acc_doubleSpinBox.setSingleStep(0.1)
        self.acc_doubleSpinBox.setProperty("value", 0.6)
        self.acc_doubleSpinBox.setObjectName("acc_doubleSpinBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.acc_doubleSpinBox)
        self.res_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.res_doubleSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.res_doubleSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.res_doubleSpinBox.setSingleStep(0.1)
        self.res_doubleSpinBox.setProperty("value", 0.6)
        self.res_doubleSpinBox.setObjectName("res_doubleSpinBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.res_doubleSpinBox)
        self.gridLayout_2.addLayout(self.formLayout_3, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 10, 281, 311))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.setEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.setEdit.setMinimumSize(QtCore.QSize(89, 25))
        self.setEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.setEdit.setObjectName("setEdit")
        self.horizontalLayout.addWidget(self.setEdit)
        self.addsetButton = QtWidgets.QPushButton(self.groupBox_3)
        self.addsetButton.setMinimumSize(QtCore.QSize(80, 10))
        self.addsetButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.addsetButton.setObjectName("addsetButton")
        self.horizontalLayout.addWidget(self.addsetButton)
        self.removesetButton = QtWidgets.QPushButton(self.groupBox_3)
        self.removesetButton.setMinimumSize(QtCore.QSize(80, 10))
        self.removesetButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.removesetButton.setObjectName("removesetButton")
        self.horizontalLayout.addWidget(self.removesetButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.setslistWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.setslistWidget.setObjectName("setslistWidget")
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.setslistWidget.addItem(item)
        self.verticalLayout.addWidget(self.setslistWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.classificationComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.classificationComboBox.setObjectName("classificationComboBox")
        self.classificationComboBox.addItem("")
        self.classificationComboBox.addItem("")
        self.classificationComboBox.addItem("")
        self.verticalLayout_3.addWidget(self.classificationComboBox)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setEnabled(True)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(preferencesDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(preferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(preferencesDialog)

    def retranslateUi(self, preferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        preferencesDialog.setWindowTitle(_translate("preferencesDialog", "Prefrences"))
        self.groupBox_2.setTitle(_translate("preferencesDialog", "Substat Weights"))
        self.label_5.setText(_translate("preferencesDialog", "HP"))
        self.label_6.setText(_translate("preferencesDialog", "DEF"))
        self.label_7.setText(_translate("preferencesDialog", "ATK"))
        self.label_8.setText(_translate("preferencesDialog", "SPD"))
        self.hp_doubleSpinBox.setSpecialValueText(_translate("preferencesDialog", "1.00"))
        self.label_9.setText(_translate("preferencesDialog", "CRI Rate"))
        self.label_10.setText(_translate("preferencesDialog", "CRI Dmg"))
        self.label_11.setText(_translate("preferencesDialog", "Accuracy"))
        self.label_12.setText(_translate("preferencesDialog", "Resistance"))
        self.groupBox_3.setTitle(_translate("preferencesDialog", "Rune Sets"))
        self.addsetButton.setText(_translate("preferencesDialog", "Add"))
        self.removesetButton.setText(_translate("preferencesDialog", "Remove"))
        __sortingEnabled = self.setslistWidget.isSortingEnabled()
        self.setslistWidget.setSortingEnabled(False)
        item = self.setslistWidget.item(0)
        item.setText(_translate("preferencesDialog", "Energy"))
        item = self.setslistWidget.item(1)
        item.setText(_translate("preferencesDialog", "Swift"))
        item = self.setslistWidget.item(2)
        item.setText(_translate("preferencesDialog", "Blade"))
        item = self.setslistWidget.item(3)
        item.setText(_translate("preferencesDialog", "Fatal"))
        item = self.setslistWidget.item(4)
        item.setText(_translate("preferencesDialog", "Despair"))
        item = self.setslistWidget.item(5)
        item.setText(_translate("preferencesDialog", "Violent"))
        item = self.setslistWidget.item(6)
        item.setText(_translate("preferencesDialog", "Focus"))
        item = self.setslistWidget.item(7)
        item.setText(_translate("preferencesDialog", "Guard"))
        item = self.setslistWidget.item(8)
        item.setText(_translate("preferencesDialog", "Endure"))
        item = self.setslistWidget.item(9)
        item.setText(_translate("preferencesDialog", "Shield"))
        item = self.setslistWidget.item(10)
        item.setText(_translate("preferencesDialog", "Revenge"))
        item = self.setslistWidget.item(11)
        item.setText(_translate("preferencesDialog", "Rage"))
        item = self.setslistWidget.item(12)
        item.setText(_translate("preferencesDialog", "Will"))
        item = self.setslistWidget.item(13)
        item.setText(_translate("preferencesDialog", "Nemesis"))
        item = self.setslistWidget.item(14)
        item.setText(_translate("preferencesDialog", "Vampire"))
        item = self.setslistWidget.item(15)
        item.setText(_translate("preferencesDialog", "Destroy"))
        item = self.setslistWidget.item(16)
        item.setText(_translate("preferencesDialog", "???"))
        self.setslistWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("preferencesDialog", "General"))
        self.groupBox_4.setTitle(_translate("preferencesDialog", "Classification"))
        self.classificationComboBox.setItemText(0, _translate("preferencesDialog", "Simple"))
        self.classificationComboBox.setItemText(1, _translate("preferencesDialog", "Complex"))
        self.classificationComboBox.setItemText(2, _translate("preferencesDialog", "Custom"))
        self.groupBox.setTitle(_translate("preferencesDialog", "Monster Types"))
        self.label.setText(_translate("preferencesDialog", "Usage: JSON style of the type \'MONS_TYPE\': {\'SETS\': [list of sets], \'SUBS\': [list of subs]"))
        self.textEdit.setHtml(_translate("preferencesDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">{\'TNK\': {    \'SETS\' : [\'Energy\', \'Guard\', \'Endure\', \'Shield\', \'Revenge\', \'Will\', \'Nemesis\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\' : [\'HP\', \'DEF\', \'RES\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'PDD\': {        \'SETS\' : [\'Fatal\', \'Rage\', \'Blade\', \'Will\', \'Nemesis\', \'Vampire\', \'Destroy\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\' : [\'ATK\', \'CR\', \'CD\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'VDD\': {        \'SETS\' : [\'Violent\', \'Blade\', \'Will\', \'Nemesis\', \'Vampire\', \'Destroy\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">     \'SUBS\' : [\'ATK\', \'CR\', \'CD\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'SDD\': {        \'SETS\' : [\'Violent\', \'Fatal\', \'Rage\', \'Will\', \'Blade\', \'Will\', \'Nemesis\', \'Vampire\',\'Destroy\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\' : [\'ATK\', \'CR\', \'CD\', \'SPD\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'ADD\': {        \'SETS\' : [\'Violent\', \'Blade\', \'Will\', \'Nemesis\', \'Vampire\', \'Destroy\', \'Revenge\', \'Focus\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\' : [\'ATK\', \'CR\', \'CD\', \'ACC\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'RDD\': {        \'SETS\' : [\'Violent\', \'Fatal\', \'Rage\', \'Vampire\', \'Blade\', \'Will\', \'Nemesis\', \'Revenge\', \'Destroy\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\' : [\'ATK\', \'CR\', \'CD\', \'RES\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'HDD\': {        \'SETS\' : [\'Violent\', \'Fatal\', \'Blade\', \'Rage\', \'Will\', \'Nemesis\', \'Vampire\', \'Energy\', \'Destroy\', \'Shield\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\' : [\'HP\', \'CR\', \'CD\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'DDD\': {        \'SETS\': [\'Violent\', \'Fatal\', \'Blade\', \'Rage\', \'Will\', \'Nemesis\', \'Vampire\', \'Guard\', \'Destroy\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\': [\'DEF\', \'CR\', \'CD\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'SSP\': {       \'SETS\': [\'Violent\', \'Swift\', \'Energy\', \'Will\', \'Nemesis\', \'Guard\', \'Shield\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\': [\'DEF\', \'HP\', \'SPD\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'RSP\': {        \'SETS\': [\'Violent\', \'Swift\', \'Energy\', \'Will\', \'Nemesis\', \'Guard\', \'Endure\', \'Shield\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">     \'SUBS\': [\'DEF\', \'HP\', \'SPD\', \'RES\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'SDM\': {        \'SETS\': [\'Swift\', \'Energy\', \'Will\', \'Nemesis\', \'Guard\', \'Shield\', \'Endure\', \'Blade\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\': [\'SPD\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'CCT\': {        \'SETS\': [\'Despair\', \'Energy\', \'Will\', \'Nemesis\', \'Guard\', \'Shield\', \'Endure\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\': [\'DEF\', \'HP\', \'SPD\', \'ACC\']},</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\"> \'BMB\': {        \'SETS\': [\'Fatal\', \'Violent\', \'Energy\', \'Will\', \'Nemesis\', \'Guard\', \'Shield\', \'Endure\', \'???\'],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" background-color:#ffffff;\">    \'SUBS\': [\'ATK\', \'SPD\', \'ACC\']}}</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("preferencesDialog", "Advanced"))

import ui_files.resources_rc