# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_list.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.runesTab = QtWidgets.QWidget()
        self.runesTab.setObjectName("runesTab")
        self.runeListWidget = QtWidgets.QListWidget(self.runesTab)
        self.runeListWidget.setGeometry(QtCore.QRect(0, 100, 791, 431))
        self.runeListWidget.setObjectName("runeListWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.runesTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 791, 62))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.slotComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.slotComboBox.setMinimumSize(QtCore.QSize(50, 20))
        self.slotComboBox.setMaximumSize(QtCore.QSize(50, 20))
        self.slotComboBox.setObjectName("slotComboBox")
        self.slotComboBox.addItem("")
        self.slotComboBox.addItem("")
        self.slotComboBox.addItem("")
        self.slotComboBox.addItem("")
        self.slotComboBox.addItem("")
        self.slotComboBox.addItem("")
        self.slotComboBox.addItem("")
        self.slotComboBox.addItem("")
        self.slotComboBox.addItem("")
        self.gridLayout.addWidget(self.slotComboBox, 0, 3, 1, 1)
        self.setComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.setComboBox.setObjectName("setComboBox")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.setComboBox.addItem("")
        self.gridLayout.addWidget(self.setComboBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 10, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 12, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 8, 1, 1, QtCore.Qt.AlignHCenter)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.minLevelComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.minLevelComboBox.setMinimumSize(QtCore.QSize(40, 0))
        self.minLevelComboBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.minLevelComboBox.setObjectName("minLevelComboBox")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.minLevelComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.minLevelComboBox)
        self.maxLevelComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.maxLevelComboBox.setMinimumSize(QtCore.QSize(40, 0))
        self.maxLevelComboBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.maxLevelComboBox.setObjectName("maxLevelComboBox")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.maxLevelComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maxLevelComboBox)
        self.gridLayout.addLayout(self.formLayout, 0, 7, 1, 1)
        self.equippedComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.equippedComboBox.setMinimumSize(QtCore.QSize(40, 0))
        self.equippedComboBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.equippedComboBox.setObjectName("equippedComboBox")
        self.equippedComboBox.addItem("")
        self.equippedComboBox.addItem("")
        self.equippedComboBox.addItem("")
        self.gridLayout.addWidget(self.equippedComboBox, 0, 11, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.mainstatComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.mainstatComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.mainstatComboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.mainstatComboBox.setObjectName("mainstatComboBox")
        self.mainstatComboBox.addItem("")
        self.mainstatComboBox.addItem("")
        self.mainstatComboBox.addItem("")
        self.mainstatComboBox.addItem("")
        self.mainstatComboBox.addItem("")
        self.mainstatComboBox.addItem("")
        self.mainstatComboBox.addItem("")
        self.mainstatComboBox.addItem("")
        self.mainstatComboBox.addItem("")
        self.gridLayout.addWidget(self.mainstatComboBox, 0, 9, 1, 1)
        self.starsComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.starsComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.starsComboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.starsComboBox.setObjectName("starsComboBox")
        self.starsComboBox.addItem("")
        self.starsComboBox.addItem("")
        self.starsComboBox.addItem("")
        self.starsComboBox.addItem("")
        self.starsComboBox.addItem("")
        self.starsComboBox.addItem("")
        self.starsComboBox.addItem("")
        self.gridLayout.addWidget(self.starsComboBox, 0, 5, 1, 1)
        self.statusComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.statusComboBox.setMinimumSize(QtCore.QSize(50, 0))
        self.statusComboBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.statusComboBox.setObjectName("statusComboBox")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.gridLayout.addWidget(self.statusComboBox, 0, 13, 1, 1)
        self.filtersButton = QtWidgets.QPushButton(self.runesTab)
        self.filtersButton.setGeometry(QtCore.QRect(10, 70, 771, 23))
        self.filtersButton.setObjectName("filtersButton")
        self.tabWidget.addTab(self.runesTab, "")
        self.plotsTab = QtWidgets.QWidget()
        self.plotsTab.setObjectName("plotsTab")
        self.tabWidget.addTab(self.plotsTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.slotComboBox.setItemText(0, _translate("MainWindow", "All"))
        self.slotComboBox.setItemText(1, _translate("MainWindow", "Even"))
        self.slotComboBox.setItemText(2, _translate("MainWindow", "Odd"))
        self.slotComboBox.setItemText(3, _translate("MainWindow", "1"))
        self.slotComboBox.setItemText(4, _translate("MainWindow", "2"))
        self.slotComboBox.setItemText(5, _translate("MainWindow", "3"))
        self.slotComboBox.setItemText(6, _translate("MainWindow", "4"))
        self.slotComboBox.setItemText(7, _translate("MainWindow", "5"))
        self.slotComboBox.setItemText(8, _translate("MainWindow", "6"))
        self.setComboBox.setCurrentText(_translate("MainWindow", "All"))
        self.setComboBox.setItemText(0, _translate("MainWindow", "All"))
        self.setComboBox.setItemText(1, _translate("MainWindow", "Swift"))
        self.setComboBox.setItemText(2, _translate("MainWindow", "Fatal"))
        self.setComboBox.setItemText(3, _translate("MainWindow", "Despair"))
        self.setComboBox.setItemText(4, _translate("MainWindow", "Violent"))
        self.setComboBox.setItemText(5, _translate("MainWindow", "Rage"))
        self.setComboBox.setItemText(6, _translate("MainWindow", "Vampire"))
        self.setComboBox.setItemText(7, _translate("MainWindow", "Energy"))
        self.setComboBox.setItemText(8, _translate("MainWindow", "Blade"))
        self.setComboBox.setItemText(9, _translate("MainWindow", "Focus"))
        self.setComboBox.setItemText(10, _translate("MainWindow", "Guard"))
        self.setComboBox.setItemText(11, _translate("MainWindow", "Shield"))
        self.setComboBox.setItemText(12, _translate("MainWindow", "Revenge"))
        self.setComboBox.setItemText(13, _translate("MainWindow", "Endure"))
        self.setComboBox.setItemText(14, _translate("MainWindow", "Will"))
        self.setComboBox.setItemText(15, _translate("MainWindow", "Nemesis"))
        self.setComboBox.setItemText(16, _translate("MainWindow", "Destroy"))
        self.label.setText(_translate("MainWindow", "Set"))
        self.label_2.setText(_translate("MainWindow", "Slot"))
        self.label_6.setText(_translate("MainWindow", "Equipped"))
        self.label_9.setText(_translate("MainWindow", "Status"))
        self.label_4.setText(_translate("MainWindow", "Level"))
        self.label_5.setText(_translate("MainWindow", "Main Stat"))
        self.label_7.setText(_translate("MainWindow", "Min"))
        self.label_8.setText(_translate("MainWindow", "Max"))
        self.minLevelComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.minLevelComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.minLevelComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.minLevelComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.minLevelComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.minLevelComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.minLevelComboBox.setItemText(6, _translate("MainWindow", "6"))
        self.minLevelComboBox.setItemText(7, _translate("MainWindow", "7"))
        self.minLevelComboBox.setItemText(8, _translate("MainWindow", "8"))
        self.minLevelComboBox.setItemText(9, _translate("MainWindow", "9"))
        self.minLevelComboBox.setItemText(10, _translate("MainWindow", "10"))
        self.minLevelComboBox.setItemText(11, _translate("MainWindow", "11"))
        self.minLevelComboBox.setItemText(12, _translate("MainWindow", "12"))
        self.minLevelComboBox.setItemText(13, _translate("MainWindow", "13"))
        self.minLevelComboBox.setItemText(14, _translate("MainWindow", "14"))
        self.minLevelComboBox.setItemText(15, _translate("MainWindow", "15"))
        self.maxLevelComboBox.setCurrentText(_translate("MainWindow", "15"))
        self.maxLevelComboBox.setItemText(0, _translate("MainWindow", "0"))
        self.maxLevelComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.maxLevelComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.maxLevelComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.maxLevelComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.maxLevelComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.maxLevelComboBox.setItemText(6, _translate("MainWindow", "6"))
        self.maxLevelComboBox.setItemText(7, _translate("MainWindow", "7"))
        self.maxLevelComboBox.setItemText(8, _translate("MainWindow", "8"))
        self.maxLevelComboBox.setItemText(9, _translate("MainWindow", "9"))
        self.maxLevelComboBox.setItemText(10, _translate("MainWindow", "10"))
        self.maxLevelComboBox.setItemText(11, _translate("MainWindow", "11"))
        self.maxLevelComboBox.setItemText(12, _translate("MainWindow", "12"))
        self.maxLevelComboBox.setItemText(13, _translate("MainWindow", "13"))
        self.maxLevelComboBox.setItemText(14, _translate("MainWindow", "14"))
        self.maxLevelComboBox.setItemText(15, _translate("MainWindow", "15"))
        self.equippedComboBox.setItemText(0, _translate("MainWindow", "All"))
        self.equippedComboBox.setItemText(1, _translate("MainWindow", "Yes"))
        self.equippedComboBox.setItemText(2, _translate("MainWindow", "No"))
        self.label_3.setText(_translate("MainWindow", "Stars"))
        self.mainstatComboBox.setItemText(0, _translate("MainWindow", "All"))
        self.mainstatComboBox.setItemText(1, _translate("MainWindow", "SPD"))
        self.mainstatComboBox.setItemText(2, _translate("MainWindow", "HP"))
        self.mainstatComboBox.setItemText(3, _translate("MainWindow", "DEF"))
        self.mainstatComboBox.setItemText(4, _translate("MainWindow", "ATK"))
        self.mainstatComboBox.setItemText(5, _translate("MainWindow", "CR"))
        self.mainstatComboBox.setItemText(6, _translate("MainWindow", "CD"))
        self.mainstatComboBox.setItemText(7, _translate("MainWindow", "ACC"))
        self.mainstatComboBox.setItemText(8, _translate("MainWindow", "RES"))
        self.starsComboBox.setItemText(0, _translate("MainWindow", "All"))
        self.starsComboBox.setItemText(1, _translate("MainWindow", "1"))
        self.starsComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.starsComboBox.setItemText(3, _translate("MainWindow", "3"))
        self.starsComboBox.setItemText(4, _translate("MainWindow", "4"))
        self.starsComboBox.setItemText(5, _translate("MainWindow", "5"))
        self.starsComboBox.setItemText(6, _translate("MainWindow", "6"))
        self.statusComboBox.setItemText(0, _translate("MainWindow", "All"))
        self.statusComboBox.setItemText(1, _translate("MainWindow", "Sell"))
        self.statusComboBox.setItemText(2, _translate("MainWindow", "Keep"))
        self.filtersButton.setText(_translate("MainWindow", "Apply Filters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.runesTab), _translate("MainWindow", "Runes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.plotsTab), _translate("MainWindow", "Plots"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

